### PR TITLE
Refactor CLI tests

### PR DESCRIPTION
**Pull request by sonro**
- Add helper types to allow concise Command Line Interface tests
- Refactor current tests to use new helper methods
- Split cli_tests.rs into smaller files

The new types are simple wrappers for the [assert_cmd](https://crates.io/crates/assert_cmd) and [tempdir](https://crates.io/crates/tempdir) crates. They contain methods that create, operate on, and remove temporary directories; including adding subdirectories, temporary files and checking the result of Commands run within them.

There are DocComments above the types and methods to describe their purpose. 

I am happy to answer questions or make changes to these interfaces.

#### ✔ Checklist:

- [x] This PR has been added to [CHANGELOG.md](https://github.com/mgrachev/dotenv-linter/blob/master/CHANGELOG.md) (at the top of the list);

### CODE REVIEW

**Comment by mgrachev** [comment]
@sonro Thanks a lot! You're awesome! ❤️

I will check this PR a bit later...

**Comment by mgrachev** [comment]
@sonro You have done excellent work! 🧨

I see some merge conflicts. Could you please update your fork from the fresh master branch?

**Comment by sonro** [comment]
Thank you @mgrachev. I may make a small testing crate based on this. Conflicts fixed.

**Comment by mgrachev** [comment]
@sonro Thank you! ❤️

**Pull request merged**
